
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: CypherUser
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: CypherDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: Not24Get
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - default

  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge