
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: CypherUser
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: CypherDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.com
      PGADMIN_DEFAULT_PASSWORD: Not24Get
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - default
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)"
      - "traefik.http.routers.pgadmin.entrypoints=web"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"

  traefik:
    image: traefik:v3.1
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
  
  java:
    image: ghcr.io/tpcypher/back/app:latest
    container_name: java_app
    working_dir: /app
    volumes:
      - ./java-app:/app
    command: ["java", "-jar", "YourApp.jar"]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.back.rule=Host(`back.localhost`)"
      - "traefik.http.routers.back.entrypoints=web"
      - "traefik.http.services.back.loadbalancer.server.port=8080"
    depends_on:
      - postgres
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    driver: bridge